### ISSUE TITLE
Landing pages design and flow errors

### ISSUE THREAD

**Issue by teddy4445** [teddy4445/lecture_website_app_generator#40]
The format of the errors: page name \ feature, error description

**Both**:
1. all forms on submitting does not check all the values are entered and legit

**Desktop:**
1. all forms on error \ success, there is no X and V icons as in the design.
2. index page, the image of the computer is not up to date
3. the desktop footer is broken - in the desktop view the footer should be a row and not a column 

**Mobile:**
1. index page - header menu, where clicking on the "who we are" the page scroll to the right place but the menu does not close.
2. contact-us page - the HTML is shown 2 times on mobile.

**Comment by noamTzi** [comment]
**Desktop:**
*16 px = 1 rem.
Please change sizes from px to rem according to the 'design system' page on the 'landing page' figma file.*

On index page, please add/change the properties as written below:

1. *header-container:*
- header-container, *properties:* padding: 0, padding-left: 9rem
- headline, suppose to be of "h1 heading" kind. *properties:* font-size: 3.5rem, line-height: 150%, margin bottom: 2rem
- paragraph, *properties:* font-size: 1.25rem, margin-bottom: 2rem
- navigation bar, *properties:* padding: 0
- navigation bar links, *properties:* padding: 0
- navigation bar logo (brand), *properties:* padding-top: 0
- button text (link-btn-big), *properties:* font-size: 1.4rem
2. *section-container with 3 steps of website creation:*
- index \ h3, *properties:* font-size: 1.5rem, line-heigt: 150%
- steps text (except purple numbers), *properties:* font-weight: 300, font-size:1.25rem, line-height: 200%, margin-right: 2rem, margin-left: 2rem
- headline, suppose to be of "h5 heading" kind. *properties:* same settings but: font-family: roboto, font-size: 24px/1.25rem
3. *div with phone image:*
- phone image, bottom margin is ending before image, please change it to be according to phone image's bottom border. Also, the image itself should be reponsive to screen size.
4. *blue container:*
- paragraph, *properties:* font-weight: 400, font-size: 1.25rem, line-height: 180%
5. *footer*
- is broken as mentioned before.

6. index page, the image of the computer is not up to date - can be founded on drive

**Comment by Hadari23** [comment]
all forms on submitting does not check all the values are entered and legit **-fixed**
all forms on error \ success, there is no X and V icons as in the design. **-fixed**
index page, the image of the computer is not up to date **-fixed**
index page - header menu, where clicking on the "who we are" the page scroll to the right place but the menu does not close. **-fixed**
contact-us page - the HTML is shown 2 times on mobile. **-fixed**

TODO:
the desktop footer is broken - in the desktop view the footer should be a row and not a column

**Comment by noamTzi** [comment]
### Desktop - continuation:

**General**
_I made many changes to the desktop file. Please verify with the Figma file mentioned later that's everything is in place. Would love to go live while you guys are fixing the website, maybe I could better help this way._

- Website:
1. On the website, please change all places where the word "product" shows up as the product's logo to "Tassel" :)
- Source of Truth in Figma:
2. All requested changes to proportions etc. made in the Figma file: "01/10/2020 - landing page - desktop - in progress". Link: https://www.figma.com/file/v6iTyKRPimE7zqOjARqy8w/?node-id=350%3A848
3. Design System changes in the Figma file: 01/10/2020 - landing page - design system - desktop - in progress. Link: https://www.figma.com/file/v6iTyKRPimE7zqOjARqy8w/?node-id=352%3A0
4. Other pages named "closed for changes" are not in use anymore.

**Contact page:**
1. A press on the "send" button leads directly to the "thank you" page without validation. Happens after writing a name and no validation to it occurs.
2. Changes were made to Headlines & text proportions.
3. _"Tell us what you have in mind"_ field should be a text box with a min-height of 250px.
4. Padding between navbar and headline should be 100px.
5. Padding between last elemnt on page and footer should be 150px.

**Join us page:**
1. A press on the "send" button leads directly to the "thank you" page without validation. Happens after writing a name and no validation to it occurs.
2. Changes were made to Headlines & text proportions.
3. Text's missing under headline here.
4. _"Tell us a little about yourself"_ field should be a text box with a min-height of 250px.
5. Padding between navbar and headline should be 100px.
6. Padding between last elemnt on page and footer should be 150px.

**Thank you _pages_:**
1. Copy was changed.
2. Icons' size changed to 40px
3. Changes were made to Headlines & text proportions.
4. In gray rectangle there should be top-padding and bottom-padding between its borders and its items of 90px.

**Sign up page**
1. A press on the "send" button leads directly to the "thank you" page without validation. Happens after writing a name and no validation to it occurs.
2. Changes were made to Headlines & text proportions.
3. _"I am a"_ radio buttons supposed to be on the text's left.
4. Padding between navbar and headline should be 100px.
5. Padding between last elemnt on page and footer should be 150px.

**Comment by noamTzi** [comment]
### Mobile:

**General:**
1. Menu exit icon - text is used instead of the icon. I uploaded the icon to the shared drive folder. Also, Icon should be exactly on top of the menu icon.
2. Menu bar and opened menu size are not responsive to screen width. I like the animation though!
3. On the website, please change all places where the word "product" shows up as the product's logo to "Tassel" :)
4. Source of Truth in Figma is right for the mobile version too.
5. Text borders - Please notice that the left border is the most left pixel of the menu button, and the right border is the most right pixel of the logo button on the menu.
6. Mobile version load time - using both browser emulator and my phone, it took a while for the mobile version to load. Until then, I saw a half of the mobile version (mostly some pages and menu+navbar) and the desktop home page.
7. Please change Noam Tz's role to "UX/UI designer" both on mobile and desktop website versions.
8. Forms:
- A press on the "send" button leads directly to the "thank you" page without validation. Happens after writing a name and no validation to it occurs.
- "Tell us a little about yourself" field and similar fields should be text boxes with a min-height of 200px.

**Home page:**
1. Team part is not according to Figma mobile file, team members should appear as a carousel. Please work with it.
- Link to Design: https://www.figma.com/file/v6iTyKRPimE7zqOjARqy8w/?node-id=403%3A6825
- Link to prototype: https://www.figma.com/proto/v6iTyKRPimE7zqOjARqy8w/landing-page?node-id=403%3A7078&viewport=239%2C792%2C0.15932603180408478&scaling=min-zoom
2. Some of the text is not responsive to screen size.
3. Some elements and text are not responsive to screen size. Examples for them are all elements on the blue container, blue sign-up button, and text at the head container.
4. images are too small on height. I prefer to use 100% height and width to fit the responsive screen and flex objects.

**Join us page:**
1. Content boxes of jobs half-open and are not responsive to screen size:
![thankyou1](https://user-images.githubusercontent.com/39398826/94990469-09e93600-0585-11eb-84e7-da370a3a2a93.png)
![thankyou2](https://user-images.githubusercontent.com/39398826/94990472-0ce42680-0585-11eb-8e36-baa9b911d62e.png)

2. Back button: please change font-size to 0.875REM (14px) and also move it to the left of the menu button.

**Share & Thank you pages**
1. Same errors as in the Desktop version.
2. Wrong proportions content cubes - when the share button is clicked then the image should spread all over the screen.
3. I'm glad the animation of the image worked, would love to learn how was it made.

### Let's talk about this one please, I think on the mobile version I can be more useful to you guys when I speak rather than write. What would be a good time for you this week?

**Comment by Hadari23** [comment]
TODO:
- 2 white lines here: https://docs.google.com/spreadsheets/d/1CYfKDqe4YRM4XT-XBqx9VFvl4UOyxHnMLL1WGS-v_xk/edit#gid=529823225
- index sliders

**Comment by noamTzi** [comment]
*** Last and hopefully least fixes for the desktop landing version:

*General:*
1. *Please do check the font sizes and weights, some I think havn't changed, maybe it's not the updated version that I see?*
2. Also, Please center the text in all buttons in website to the middle if the button: top-down and left-right.
3. Please change all input labels to 16px in size (=1rem), They are still very big, I'm sorry for wasting your time on this.
4. Please change all inputs like name, email etc. height to 40px (=1.25rem), *Notice:* (not in text boxes (e.g. 'what would you like to tell us') in join us, contact us etc.!)
5. *Secondary* buttons in gray or purple [RGB code: 828282 or 5A67D8] suppose to be filled with *purple [RGB code: 5A67D8]*. If disabled then would be filled in all situatuations with gray [RGB code: 828282], and not perform a hover animation. (Appearrs in design system file in Figma-Landing Page).


*Home:*
1. header-container:
- steps text (except purple numbers), properties: font-weight: 300, font-size:1.25rem, line-height: 200%, margin-right: 2rem, margin-left: 2rem
2. blue container:
- paragraph, properties: font-weight: 400, font-size: 1.25rem, line-height: 180%

*Join us page:*
1. I think the boxes are too big, especially when there is one line of text.
2. The text here (except title, subtitles) should be 16px = 1rem.
![image](https://user-images.githubusercontent.com/39398826/95582024-ace8f680-0a42-11eb-9b99-0ec543c19727.png)
3. button is huge. The text - also should be smaller - 1.4 at all secondary buttons.
4. Are you... title - align to the left + font size should be 2.5rem:
![image](https://user-images.githubusercontent.com/39398826/95583266-862bbf80-0a44-11eb-8a5c-acba4c51c07f.png)
5. email input here does not need to be checked in user-side. Do check for mallicious code please if possible in all inputs and specifically here in a tranparent way.
![image](https://user-images.githubusercontent.com/39398826/95583352-a9566f00-0a44-11eb-8d7f-b69f11621c60.png)
6. Phone input - doesn't accept '-'. Please add this line to copy of error if a '-' happen to be there:
"Please enter only numbers"
![image](https://user-images.githubusercontent.com/39398826/95583578-06522500-0a45-11eb-9599-65f6a0c57358.png)
7. "send" takes a while, and there's no indication to a bug in it or that the server just thinks. Can we add there a "page" that will hide with half-tranparent color the main website with the message "we're sending your message" and a load-bar (I'll ask Ayelet about the copy but I'd like to know if the whole idea is possible?).

*Contact us page:*
*Join us page:*
1. I think the boxes are too big, especially when there is one line of text.
2. button is huge. The text - also should be smaller - 1.4 at all secondary buttons.
3. "send" takes a while, and there's no indication to a bug in it or that the server just thinks. Can we add there a "page" that will hide with half-tranparent color the main website with the message "we're sending your message" and a load-bar (I'll ask Ayelet about the copy but I'd like to know if the whole idea is possible?).

I think that pretty much all for desktop version. Hadar already fixes the other margin/padding issues (Thank you!)

**Comment by noamTzi** [comment]
### Mobile

**General:**
1. Please make sure the logo is aligned to right of the menu bar.
![image](https://user-images.githubusercontent.com/39398826/95584510-875dec00-0a46-11eb-8ac6-ce17e21139ca.png)
2. I added a sphera logo in menu. Hadar saw places I added it in Figma file.
3. Main page and menu act funny when width is over 870px: some of the top of main page (including menu) disappearrs. May you please have a look there?
![image](https://user-images.githubusercontent.com/39398826/95584731-dc016700-0a46-11eb-8b29-1cb0e1302cf8.png)
4. Menu's X icon is not the right one - I put it in the icons' folder in the common drive folder.
5. Menu links on hover turn blue. Should be in purple please [RGB code: 5A67D8].

**Join us page:**
1. email input here does not need to be checked in user-side. Do check for mallicious code please if possible in all inputs and specifically here in a tranparent way.
2. send button: Secondary button here in gray or purple [RGB code: 828282 or 5A67D8] suppose to be filled with purple [RGB code: 5A67D8]. If disabled then would be filled in all situatuations with gray [RGB code: 828282], and not perform a hover animation. (Appearrs in design system file in Figma-Landing Page).
3. Share this animation causes this:
![image](https://user-images.githubusercontent.com/39398826/95585204-96916980-0a47-11eb-99db-3743d5795e62.png)
square appearrs too low and too right in screen.
Also - X icon not the right one - please change it according to common icon folder.

**Comment by teddy4445** [comment]
Reviewed, fixed... Ready for deploy
